-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 23:30:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app_test` ;

-- -----------------------------------------------------
-- Schema app_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_test` DEFAULT CHARACTER SET utf8 ;
USE `app_test` ;

-- -----------------------------------------------------
-- Table `app_test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_test`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(255) NOT NULL COMMENT 'ユーザー名',
  `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
  `password` VARCHAR(255) NOT NULL COMMENT 'パスワード',
  `remember_token` VARCHAR(255) NULL DEFAULT NULL COMMENT 'トークン',
  `role` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '権限',
  `updated_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '更新日時',
  `created_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '作成日時',
  `delete_datetime` DATETIME NULL DEFAULT NULL COMMENT '削除日時',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_test`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_test`.`password_resets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
  `token` VARCHAR(255) NOT NULL COMMENT 'トークン',
  `created_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '作成日時',
  `delete_datetime` DATETIME NULL DEFAULT NULL COMMENT '削除日時',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_test`.`backend_password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_test`.`backend_password_resets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
  `token` VARCHAR(255) NOT NULL COMMENT 'トークン',
  `created_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '作成日時',
  `delete_datetime` DATETIME NULL DEFAULT NULL COMMENT '削除日時',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`, `token`),
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_test`.`backend_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_test`.`backend_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(255) NOT NULL COMMENT 'ユーザー名',
  `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
  `password` VARCHAR(255) NOT NULL COMMENT 'パスワード',
  `remember_token` VARCHAR(255) NULL DEFAULT NULL COMMENT 'トークン',
  `role` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '権限',
  `updated_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '更新日時',
  `created_at` TIMESTAMP(2) NULL DEFAULT NULL COMMENT '作成日時',
  `delete_datetime` DATETIME NULL DEFAULT NULL COMMENT '削除日時',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
